apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-mongodb-app
  namespace: default
spec:
  project: default

  source:
    repoURL: https://github.com/dvorkinguy/demo-mongodb-app.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true